project:
    type: website
    output-dir: ../

website:
    title: "Scientific Computing"
    sidebar:
        contents: auto
    search: true
    page-navigation: true



subtitle: "Scientific Computing"
author: "Prof. Calvin"
  
jupyter: python3

format:
    html:
        toc: true
        theme: darkly 
        code-line-numbers: true
        code-tools:
            source: true
            toggle: false
            caption: none
    revealjs: 
        theme: dark
        mainfont: monospace
        slide-number: true
        show-slide-number: all
        width: 1050
        height: 700
        footer: "[Home](../index.html)"
        output-ext: rjs.html

execute:
    echo: true
    cache: true
    freeze: true  # never re-render during project render